run_cpu_tests:
  image: tensorflow/tensorflow:latest-py3
  stage: test

  script:
    - apt-get update
    - apt-get --yes install git
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install nose
    - cd ${CI_PROJECT_DIR}
    - nosetests
