run_cpu_tests:
  image: tensorflow/tensorflow:latest-py3
  stage: test

  script:
    - pip install Cython --user
    - pip install nose --user
    - pip install -e ${CI_PROJECT_DIR} --user
    - cd ${CI_PROJECT_DIR}
    - nosetests
