run_fast_tests:
  image: tensorflow/tensorflow:latest-py3
  stage: test

  script:
    - apt-get update
    - apt-get --yes install git
    - export GIT_SSL_NO_VERIFY=1
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_DIR}
    - pip install -U pytest
    - pytest -v -m "not slow"
  tags: [docker]

run_slow_tests:
  image: tensorflow/tensorflow:latest-py3
  stage: test

  script:
    - apt-get update
    - apt-get --yes install git
    - export GIT_SSL_NO_VERIFY=1
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - cd ${CI_PROJECT_DIR}
    - pip install -U pytest
    - pytest -s -v -m "slow"
  tags: [docker]
